// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// longest_common_substring
StringVector longest_common_substring(StringVector str1, StringVector str2);
RcppExport SEXP _lcs_longest_common_substring(SEXP str1SEXP, SEXP str2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type str1(str1SEXP);
    Rcpp::traits::input_parameter< StringVector >::type str2(str2SEXP);
    rcpp_result_gen = Rcpp::wrap(longest_common_substring(str1, str2));
    return rcpp_result_gen;
END_RCPP
}
// longest_common_substring_all
List longest_common_substring_all(StringVector str1, StringVector str2);
RcppExport SEXP _lcs_longest_common_substring_all(SEXP str1SEXP, SEXP str2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type str1(str1SEXP);
    Rcpp::traits::input_parameter< StringVector >::type str2(str2SEXP);
    rcpp_result_gen = Rcpp::wrap(longest_common_substring_all(str1, str2));
    return rcpp_result_gen;
END_RCPP
}
// longest_common_subsequence
StringVector longest_common_subsequence(StringVector str1, StringVector str2);
RcppExport SEXP _lcs_longest_common_subsequence(SEXP str1SEXP, SEXP str2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type str1(str1SEXP);
    Rcpp::traits::input_parameter< StringVector >::type str2(str2SEXP);
    rcpp_result_gen = Rcpp::wrap(longest_common_subsequence(str1, str2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lcs_longest_common_substring", (DL_FUNC) &_lcs_longest_common_substring, 2},
    {"_lcs_longest_common_substring_all", (DL_FUNC) &_lcs_longest_common_substring_all, 2},
    {"_lcs_longest_common_subsequence", (DL_FUNC) &_lcs_longest_common_subsequence, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_lcs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
