# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the longest common substring of two strings.
#'
#' @param str1 A character vector
#' @param str2 A character vector
#' @export
longest_common_substring <- function(str1, str2) {
    .Call(`_lcs_longest_common_substring`, str1, str2)
}

