# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

longest_common_substring <- function(str1, str2) {
    .Call(`_lcs_longest_common_substring`, str1, str2)
}

rcpp_hello_world <- function() {
    .Call(`_lcs_rcpp_hello_world`)
}

