# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Longest common substring
#' 
#' Find the longest common substring of two strings.
#' 
#' Implemented in C++. The algorithm runs in \code{O(n*r)} time where \code{n} 
#' and \code{r} are the lengths of the two strings.
#'
#' @param str1 A character vector
#' @param str2 A character vector
#' @return A character vector of the same length as \code{str1} and 
#'   \code{str2}.
#' @examples
#' longest_common_substring('abcdefgh', 'xxxbcdexxx')
#' @export
longest_common_substring <- function(str1, str2) {
    .Call(`_lcs_longest_common_substring`, str1, str2)
}

